apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *" # 标准的Unix Cron格式表达式
  concurrencyPolicy: Forbid  # 处理:当前job还没执行完,一个新的job就产生了
  startingDeadlineSeconds: 200 # 时间窗口大小
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure


#1.concurrencyPolicy=Allow，这也是默认情况，这意味着这些 Job 可以同时存在
#2.concurrencyPolicy=Forbid，这意味着不会创建新的 Pod，该创建周期被跳过
#3.concurrencyPolicy=Replace，这意味着新产生的 Job 会替换旧的、没有执行完的 Job

#  如果某一次 Job 创建失败，这次创建就会被标记为“miss”。当在指定的时间窗口内，miss 的数目达到 100 时，那么 CronJob 会停止再创建这个 Job
