apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 2 # 一个 Job 在任意时间最多可以启动多少个 Pod 同时运行
  completions: 4 # Job 至少要完成的 Pod 数目，即 Job 的最小完成数
  template:
    spec:
      containers:
        - name: pi
          image: resouer/ubuntu-bc
          command: ["sh", "-c", "echo 'scale=100; 4*a(1)' | bc -l "]
      restartPolicy: Never
  backoffLimit: 4   # 重试次数
  activeDeadlineSeconds: 100 # 最长运行时间  Pod 的状态里看到终止的原因是 reason: DeadlineExceeded
